### PR TITLE
Fix #13280

### LINKED ISSUE #13280: incorrect typeof behavior
typeof doesn't work in attributes with array, function and void types
```nemerle
[Test(typeof(array[int]))] //error : invalid type in attribute parameter
class TypeOfIntArray { }

[Test(typeof(array[_]))] //error : invalid type in attribute parameter
class TypeOfGenericArray { }

[Test(typeof(int*string))] //error : invalid type in attribute parameter
class TypeOfIntStringTuple { }

[Test(typeof(_*_))] //error : invalid type in attribute parameter
class TypeOfGenericTuple { }

[Test(typeof(int -> int))] //error : invalid type in attribute parameter
class TypeOfIntToIntFunc { }

[Test(typeof(_ -> _))] //error : invalid type in attribute parameter
class TypeOfGenericFunc { }

[Test(typeof(void))] //error : invalid type in attribute parameter
class TypeOfVoid { }
```
typeof on generic functions produce incorrent value
```nemerle
typeof(_ -> _)   |> typeString |> WriteLine; //Function`2[Object, Object] expected Function`2
```
incorrect typeof behavior on generic array
```nemerle
typeof(array[_]) |> typeString |> WriteLine; //Object[] expected error
```
incorrect typeof behavior on unbound generic type in generic arguments
```nemerle
typeof(List[Dictionary[int, _]]) typeString |> WriteLine; List`1[Dictionary`2[Int32, Object]] expected error
```

### PR DESCRIPTION
**Pull request by stdray**
subj

### CODE REVIEW

**Comment by NN---** [comment]
What is the purpose of typeof(array[_]) if you can write typeof(array[object]) ?

**Comment by stdray** [comment]
@someone-with-default-username I see https://github.com/rsdn/nemerle/pull/13281/files#diff-ab7ea1fbb7d6fb4cff06f6bcb90b123fR97. But this is a general behavior of nemerle typeof operator.

**Comment by someone-with-default-username** [comment]
In typeof() operator I expect to get System.Type for exactly specified Nemerle type, and get compilation error, if it is not possible (e.g partially bounded generics).

Here we see type inference leak: array[_] automatically and silently bounded to array[System.Object]. Compilation error must be here - there is no System.Type for opened array type.

In case of function type _ -> _ I expect to get Function`2, not automatically bounded to Function`2[Object, Object].

**Comment by stdray** [comment]
@someone-with-default-username It' is not attributes related problem. This code
```nemerle
using Nemerle.Collections;
using System;
using System.Console;

def typeString(type : Type)
{
  def args = type.GenericTypeArguments;
  if(args.Length > 0)
  {
    def argsStr = string.Join(", ", args.Map(typeString));
    $"$(type.Name)[$argsStr]"
  }
  else type.Name
}
typeof(array[_]) |> typeString |> WriteLine;
typeof(_ -> _)   |> typeString |> WriteLine;
```
produce the same result:
```
Object[]
Function`2[Object, Object]
```
If we want a more obvious behavior, we have to change the implementation of the operator typeof. This will affect a lot more parts of the compiler in comparison with that particular bug. It's just another problem, i'm think.

**Comment by stdray** [comment]
@NN--- I don't know what is the purpose of typeof(array[_]), but you can write that.

**Comment by NN---** [comment]
@stdray Then it is a bug if this is allowed.
Actually C# allows to write typeof without specifying generics and then you get a generic type as you expect:

```c#
using System;

public class Test
{
	public static void Main()
	{
		Console.WriteLine(typeof(System.Collections.Generic.List<>));
		// your code goes here
	}
}
```

System.Collections.Generic.List`1[T]


http://ideone.com/Ye3sAy

**Comment by stdray** [comment]
@NN--- 
Maybe, it is a bug. But this problem is not related with usage typeof in attributes https://github.com/rsdn/nemerle/pull/13281#issuecomment-69743877. Because typeof in attributes have only once difference:
>Custom attributes are only permitted to reference open generic types, which are generic types for which no type arguments are supplied, and closed constructed generic types, which supply arguments for all type parameters.
 - http://msdn.microsoft.com/en-us/library/ms173129.aspx

**Comment by stdray** [comment]
@NN---, @someone-with-default-username fix this problem

**Comment by stdray** [comment]
done

**Pull request merged**
